spring:
  application:
    name: distributed-api-rate-limiter

  datasource:
    url: jdbc:mysql://localhost:3306/ratelimiterdb
    username: root
    password: Nani123@

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080